### ISSUE TITLE
Assert does not work with ArraySegment

### ISSUE THREAD

**Issue by xplicit** [nunit/nunitv2#39]
This code throws an exception on .NET, while it should be passed. With mono 3.12 it works. The same issue with NUnit v 3.0

```
 Assert.AreEqual(new ArraySegment<byte>(),new ArraySegment<byte>());
```

**Comment by rprouse** [comment]
We won't be releasing another 2.6 release, so I have moved this to nunit/nunit#477  and am closing it here as won't fix. Thanks for reporting.
