### ISSUE TITLE
Nunit 2.6.4 release link times out

### ISSUE THREAD

**Issue by bbatha** [nunit/nunitv2#44]
I can no longer download the [2.6.4 release zip](https://github.com/nunit/nunitv2/releases/download/2.6.4/NUnit-2.6.4.zip), the link times out.

**Comment by CharliePoole** [comment]
As far as I can tell, it's a GitHub problem. All of the release packages time out. I'll monitor it later today to see if the problem is corrected.

**Comment by CharliePoole** [comment]
GitHub's problem has corrected itself.
